### ISSUE TITLE
Release 3.0 zip is corrupted and  brightness range not varying significantly

### ISSUE THREAD

**Issue by lalitsom** [Nixes/DesktopMonitorBrightness#38]
Hey,
  Your latest release 3.0 is not getting extracted from zip file on my windows 7 32 bit pc.
 May be it's corrupted or something. v2.0 works fine though, but in 2.0 range of brightness is not varying significantly. As compared to other software I use (Desktop Lighter).

**Comment by Nixes** [comment]
Thanks for bringing this to my attention. The zip I uploaded uses a different compression than most zip files as I can open it fine on 7zip. I have uploaded [another one](https://github.com/Nixes/DesktopMonitorBrightness/releases/download/v0.3/windows_x86_DesktopMonitorBrightness_v03_fixed.zip) that should work better for you.

**Comment by Nixes** [comment]
The brightness thing I'm not sure about. I'll look into what Desktop Lighter is doing when I have more time. Thanks.

**Comment by Nixes** [comment]
Are you using this on more one screen? If so did you notice any differences between screens with each utility?

**Comment by lalitsom** [comment]
No, I'm not using this on more than one screen.

I have also tried to create a similar kind of utility using using c# wpf. 
using   SetDeviceGammaRamp() function from gdi32.dll,  but still not getting what I expected for.
what I am trying to do is , get almost dark screen when set to minimum brightness.
so give me heads up if you find anything.

**Comment by lalitsom** [comment]
There is one Difference between your app and DLighter.
If I change brightness from your app, the changes also get reflected in monitor properties (which can be opened by pressing hardkeys on bottom of monitor).
but when Dlighter change the brightness of monitor, there is no change in actual value of monitor brightness properties.

**Comment by Nixes** [comment]
It sounds like it might be manipulating contrast or some other display property to fake a lower brightness.
